// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcS_R6rX4M96ZV_zMB3bH9ePdegj2OWYI',
    appId: '1:635177722315:web:030d916aff3ca6be08964e',
    messagingSenderId: '635177722315',
    projectId: 'badminton-court-booking-cc9f0',
    authDomain: 'badminton-court-booking-cc9f0.firebaseapp.com',
    storageBucket: 'badminton-court-booking-cc9f0.appspot.com',
    measurementId: 'G-PJRK0T6547',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWEtfj3DRJRkWUUB5p4HIF1gtn_oPPeq0',
    appId: '1:635177722315:android:a582125e33c407e008964e',
    messagingSenderId: '635177722315',
    projectId: 'badminton-court-booking-cc9f0',
    storageBucket: 'badminton-court-booking-cc9f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmHmCa5n4MjMVjPIgnEJgQn5ouAR9JnDU',
    appId: '1:635177722315:ios:94003906b6a22f8a08964e',
    messagingSenderId: '635177722315',
    projectId: 'badminton-court-booking-cc9f0',
    storageBucket: 'badminton-court-booking-cc9f0.appspot.com',
    iosClientId: '635177722315-fve32fmnbnq782o42c1tttrhlpud6gso.apps.googleusercontent.com',
    iosBundleId: 'com.example.badmintonCourtBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmHmCa5n4MjMVjPIgnEJgQn5ouAR9JnDU',
    appId: '1:635177722315:ios:94003906b6a22f8a08964e',
    messagingSenderId: '635177722315',
    projectId: 'badminton-court-booking-cc9f0',
    storageBucket: 'badminton-court-booking-cc9f0.appspot.com',
    iosClientId: '635177722315-fve32fmnbnq782o42c1tttrhlpud6gso.apps.googleusercontent.com',
    iosBundleId: 'com.example.badmintonCourtBookingApp',
  );
}
